### ISSUE TITLE
ropp-ufo does not clone

### ISSUE THREAD

**Issue by Dooruk** [GEOS-ESM/jedi_bundle#33]
@mjmurph needs to access ROPP operators.

I see that `ropp-ufo` is an optional bundle, however I can't locate the source repo. Below points to a jcsda-internal location which is not there:

https://github.com/JCSDA-internal/fv3-jedi/blob/821ac6243aaad771386bf1cac0007e226c55d67a/CI/buildspec_intel.yml#L118-L119

I read in JEDI docs that `ropp-ufo` is an EUMETSAT dependency. So perhaps this now resides at an external github source and we need to find it. @danholdaway perhaps you have some insight? If not I can ask the JCSDA folks.

Since this is an optional dependency, while building we need to turn off the ecbuild flags pointed here within the jedi_bundle:

https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/jedi-components/fv3-jedi/build.html#optional-observation-operators

**Comment by danholdaway** [comment]
@Dooruk the repo may be private and you don't have access to it. Even though you have access to JCSDA-internal it doesn't mean you have access to every repo, only those which you have permission to view via the teams that you're in. Since ropp is not open source code the JCSDA is not permitted to redistribute it. Michael may need to sign an agreement to use Ropp and then he'll be able to access it and then jedi_bundle will be able to build it.

**Comment by Dooruk** [comment]
Oh I see, thanks for the explanation, that makes much more sense. Michael just told me they figured it out with Francois and has a local build with ropp.
